DROP DATABASE IF EXISTS ProyectoFinal;
CREATE DATABASE IF NOT EXISTS ProyectoFinal;
USE ProyectoFinal;

## CREACION DE TABLA DE USUARIOS
CREATE TABLE Usuarios (
    idUsuario INT AUTO_INCREMENT PRIMARY KEY,
    nombre VARCHAR(50) NOT NULL,
    contrasenia VARCHAR(100) NOT NULL,
    email VARCHAR(100) NOT NULL UNIQUE,
	residencia VARCHAR(50),
    numTelf VARCHAR(15) NOT NULL UNIQUE
);

## CREACION DE TABLA DE ALOJAMIENTOS
CREATE TABLE Alojamientos (
    idAlojamiento INT AUTO_INCREMENT PRIMARY KEY,
    nombre VARCHAR(100) NOT NULL,
    imagen VARCHAR(255),
    imagen1 VARCHAR(255),
    imagen2 VARCHAR(255),
    tipo SET('Casa Rural', 'Hotel', 'Apartamento', 'Camping'),
    descripcion TEXT,
    descripcionlarga TEXT,
	servicios SET('Wifi', 'Cocina', 'Secadora', 'Calefacción', 'TV', 'Aire Acondicionado', 'Secador de Pelo'),
    prestaciones SET('Piscina', 'Aparcamiento gratuito', 'Cuna', 'Apto para fumadores', 'Barbacoa', 'Chimenea interior'), 
    localizacion VARCHAR(100) NOT NULL,
    region VARCHAR(50) NOT NULL,
    valoracion INT CHECK (valoracion >= 1 AND valoracion <= 5) NOT NULL,
    capacidad INT NOT NULL,
    precio DECIMAL(10 , 2 ) NOT NULL,
    numTelf VARCHAR(9) NOT NULL UNIQUE,
    numHabs INT NOT NULL,
    habsDisponibles BOOLEAN DEFAULT TRUE,
	lavabos INT NOT NULL DEFAULT 1
);

## CREACION DE TABLAS DE ACTIVIDADES
CREATE TABLE Actividades (
    idActividad INT AUTO_INCREMENT PRIMARY KEY,
    nombre VARCHAR(100) NOT NULL,
    imagen VARCHAR(255),
    imagen1 VARCHAR(255),
    imagen2 VARCHAR(255),
    localizacion VARCHAR(100) NOT NULL,
    region VARCHAR(50) NOT NULL,
    precio DECIMAL(10 , 2 ) NOT NULL,
    duracion INT NOT NULL,
    dificultad ENUM('Baja', 'Media', 'Alta') NOT NULL,
    numTelf VARCHAR(9) NOT NULL UNIQUE,
    tipo SET('Aventura','Visitar','Animales','Costeras'),
    categoria SET('Senderismo', 'Ciclismo de montaña', 'Turismo cultural', 'Pesca deportiva', 'Avistamiento de aves', 'Ecoturismo', 'Rutas a caballo', 'Agricultura y huertos', 'Fotografía de naturaleza', 'Observación astronómica', 'Escalada en roca'),
    descripcion TEXT,
    descripcionlarga TEXT,
    fechaInicio DATE,
    hora TIME,
    plazasDisponibles INT
);


## CREACION DE TABLA DE RESERVAS
CREATE TABLE Reserva (
    idReserva INT AUTO_INCREMENT PRIMARY KEY,
    fechaEntrada DATE NOT NULL,
    fechaSalida DATE NOT NULL,
    numPersonas INT NOT NULL,
    estadoReserva ENUM('Pendiente', 'Confirmada', 'Cancelada'),
    numReserva VARCHAR(20) UNIQUE,
	totalPrecio DECIMAL,
	idUsuario INT,
	idAlojamiento INT,
	idActividad INT,
	idComentario INT,
	FOREIGN KEY (idUsuario) REFERENCES Usuarios(idUsuario),
	FOREIGN KEY (idAlojamiento) REFERENCES Alojamientos(idAlojamiento),
	FOREIGN KEY (idActividad) REFERENCES Actividades(idActividad)
);

## CREACION DE TABLA DE TARJETA BANCARIA
CREATE TABLE TarjetaBancaria (
    idtarjeta INT AUTO_INCREMENT PRIMARY KEY,
    nombretitular VARCHAR(255),
    numerotarjeta VARCHAR(16),
	fechacaducidad DATE,
    cvv VARCHAR(3),
    idUsuario INT,
    FOREIGN KEY (idUsuario) REFERENCES Usuarios(idUsuario)
);


## INSERTS DE USUARIOS
INSERT INTO Usuarios (nombre, contrasenia, email, numTelf, residencia) 
VALUES 
('Juan', 'contraseña123', 'juangarcia@example.com', '123456789', 'Madrid'),
('María', 'password456', 'marialopez@example.com', '987654321', 'Barcelona'),
('Carlos', 'clave789', 'carlosmartinez@example.com', '456123789', 'Sevilla');





# INSERTS DE CASAS RURALES
INSERT INTO Alojamientos (nombre, imagen, imagen1, imagen2, tipo, descripcion, descripcionlarga, servicios, prestaciones, localizacion, region, valoracion, capacidad, precio, numTelf, numHabs, habsDisponibles, lavabos) VALUES 
('Casa Rural La Encina', 'ImagenProducto imagenProducto1', 'ImagenSecundaria casarural1secundaria1', 'ImagenSecundaria casarural1secundaria2', 'Casa Rural', 'Descubre un rincón de paz en esta casa rural situada en plena naturaleza.', 'Descubre un remanso de paz en esta encantadora casa rural situada en plena naturaleza en Molina de Aragón. Disfruta de la tranquilidad mientras te relajas con las impresionantes vistas panorámicas que ofrece. La combinación de comodidades modernas y el encanto rústico harán que te sientas como en casa desde el primer momento. Esta casa rural cuenta con todas las comodidades necesarias para una estancia relajante, incluyendo conexión Wi-Fi gratuita y una cocina completamente equipada. Además, podrás disfrutar de servicios adicionales como aparcamiento gratuito y acceso a una piscina para refrescarte en los días calurosos.', 'Cocina', 'Aparcamiento gratuito,Piscina', 'Molina de Aragón, Guadalajara', 'Guadalajara', 4, 8, 290.00, '622456780', 4, TRUE, 2),
('Casa Rural El Olivo', 'ImagenProducto imagenProducto2', 'ImagenSecundaria casarural2secundaria1', 'ImagenSecundaria casarural2secundaria2', 'Casa Rural', 'Disfruta de un refugio en plena naturaleza en esta casa rural con olivar y piscina privada.', 'Descubre un oasis de serenidad en esta encantadora casa rural rodeada de olivares y con una piscina privada que invita al relax en Cervera de Pisuerga. Disfruta de la tranquilidad y desconecta del ajetreo diario mientras te sumerges en el encanto rústico de este lugar. Con una cocina totalmente equipada y conexión Wi-Fi gratuita, tendrás todo lo que necesitas para una estancia confortable. Además, podrás disfrutar de servicios como aparcamiento gratuito y la posibilidad de solicitar una cuna para los más pequeños.', 'Cocina,TV', 'Aparcamiento gratuito,Cuna', 'Cervera de Pisuerga, Palencia', 'Palencia',  5, 6, 120.00, '634467081', 3, TRUE, 3),
('Casa Rural El Roble', 'ImagenProducto imagenProducto3', 'ImagenSecundaria casarural3secundaria1', 'ImagenSecundaria casarural3secundaria2', 'Casa Rural', 'Descubre la esencia rural en esta casa de estilo rústico con jardín y vistas al monte.', 'Descubre la auténtica esencia rural en esta encantadora casa de estilo rústico en Villablino, León. Disfruta de su hermoso jardín y de las vistas impresionantes al monte que te rodea. La combinación de comodidades modernas y detalles tradicionales harán que tu estancia sea inolvidable. Equipada con todas las comodidades necesarias, como conexión Wi-Fi gratuita y cocina totalmente equipada, esta casa rural te ofrece el espacio perfecto para relajarte y desconectar. Además, podrás disfrutar de servicios adicionales como aparcamiento gratuito y una acogedora chimenea interior para las noches frescas.', 'Wifi,Calefacción', 'Aparcamiento gratuito,Chimenea interior', 'Villablino, León', 'León', 3, 10, 210.00, '645338912', 5, TRUE, 2),
('Casa Rural Entre Viñedos', 'ImagenProducto imagenProducto4', 'ImagenSecundaria casarural4secundaria1', 'ImagenSecundaria casarural4secundaria2', 'Casa Rural', 'Sumérgete en la cultura del vino en esta casa rural entre viñedos con bodega y catas de vino.', 'Casa rural entre viñedos con bodega y catas de vino. Disfruta de una experiencia única rodeado de viñedos y degustando vinos locales en nuestra bodega. La combinación de comodidades modernas y la belleza natural del entorno hacen de esta casa rural el lugar perfecto para relajarse y disfrutar de la tranquilidad. Además, podrás disfrutar de servicios como cocina completamente equipada, conexión Wi-Fi gratuita y aparcamiento gratuito.', 'Wifi,Cocina', 'Aparcamiento gratuito,Barbacoa', 'Aliste, Zamora', 'Zamora', 4, 12, 230.00, '656789023', 6, TRUE, 1),
('Casa Rural El Patio Andaluz', 'ImagenProducto imagenProducto5', 'ImagenSecundaria casarural5secundaria1', 'ImagenSecundaria casarural5secundaria2', 'Casa Rural', 'Disfruta de la autenticidad del sur de España en esta casa rural con patio andaluz y huerto ecológico.', 'Casa rural con patio andaluz y huerto ecológico. Sumérgete en la cultura andaluza y disfruta de la tranquilidad de nuestro patio interior y del aroma fresco de nuestro huerto ecológico. Equipada con todas las comodidades modernas, como conexión Wi-Fi gratuita y aire acondicionado, esta casa rural es el lugar perfecto para desconectar y relajarse. Además, podrás disfrutar de servicios como aparcamiento gratuito y una acogedora chimenea interior para las noches frescas.', 'Cocina,Aire Acondicionado', 'Aparcamiento gratuito,Chimenea interior', 'Ayna, Albacete', 'Albacete', 1, 7, 215.00, '667890034', 3, TRUE, 2),
('Casa Rural El Pinar', 'ImagenProducto imagenProducto6', 'ImagenSecundaria casarural6secundaria1', 'ImagenSecundaria casarural6secundaria2', 'Casa Rural', 'Descubre un paraíso natural en esta casa rural rodeada de pinos y cerca de rutas de senderismo.', 'Casa rural rodeada de pinos y cerca de rutas de senderismo. Sumérgete en la naturaleza y disfruta de la paz y tranquilidad que ofrece nuestro entorno natural. Equipada con todas las comodidades necesarias, como conexión Wi-Fi gratuita y cocina totalmente equipada, esta casa rural es el lugar ideal para relajarse y disfrutar de la belleza natural que te rodea. Además, podrás disfrutar de servicios como aparcamiento gratuito, piscina y una acogedora chimenea interior para las noches frescas.', 'Cocina,TV', 'Aparcamiento gratuito,Piscina,Chimenea interior', 'Almadén, Ciudad Real', 'Ciudad Real', 5, 9, 110.00, '600901245', 4, TRUE, 3),
('Casa Rural Los Pinos de Prades', 'ImagenProducto imagenProducto7', 'ImagenSecundaria casarural7secundaria1', 'ImagenSecundaria casarural7secundaria2', 'Casa Rural', 'Disfruta de un retiro tranquilo en esta casa rural en el corazón de Prades con chimenea y vistas panorámicas.', 'Casa rural en Prades, Tarragona, con chimenea y vistas panorámicas. Escápate del bullicio de la ciudad y relájate en nuestra acogedora casa rural rodeada de naturaleza. Equipada con todas las comodidades necesarias, como conexión Wi-Fi gratuita y cocina totalmente equipada, esta casa rural es el lugar perfecto para desconectar y disfrutar de la tranquilidad. Además, podrás disfrutar de servicios como aparcamiento gratuito y una barbacoa para disfrutar de deliciosas comidas al aire libre.', 'Cocina', 'Aparcamiento gratuito,Barbacoa', 'Prades, Tarragona', 'Tarragona', 5, 6, 155.00, '611723467', 3, TRUE, 1),
('Casa Rural Los Pinos', 'ImagenProducto imagenProducto8', 'ImagenSecundaria casarural8secundaria1', 'ImagenSecundaria casarural8secundaria2', 'Casa Rural', 'Disfruta de un retiro tranquilo en esta casa rural en el bosque con chimenea y vistas panorámicas.', 'Casa rural en el bosque con chimenea y vistas panorámicas. Escápate del bullicio de la ciudad y relájate en nuestra acogedora casa rural rodeada de naturaleza. Equipada con todas las comodidades necesarias, como conexión Wi-Fi gratuita y cocina totalmente equipada, esta casa rural es el lugar perfecto para desconectar y disfrutar de la tranquilidad. Además, podrás disfrutar de servicios como aparcamiento gratuito y una barbacoa para disfrutar de deliciosas comidas al aire libre.', 'Cocina', 'Aparcamiento gratuito,Barbacoa', 'Oliete, Teruel', 'Teruel', 5, 6, 105.00, '690723467', 3, TRUE, 1),
('Casa Rural La Cabaña', 'ImagenProducto imagenProducto9', 'ImagenSecundaria casarural9secundaria1', 'ImagenSecundaria casarural9secundaria2', 'Casa Rural', 'Sumérgete en la serenidad absoluta en esta casa rural con cabaña de madera.', 'Casa rural con cabaña de madera y tranquilidad absoluta. Escapa del estrés diario y disfruta de la paz y tranquilidad que ofrece nuestra encantadora cabaña de madera. Equipada con todas las comodidades modernas, como conexión Wi-Fi gratuita y cocina completamente equipada, esta casa rural es el lugar perfecto para relajarse y desconectar. Además, podrás disfrutar de servicios como aparcamiento gratuito y la posibilidad de solicitar una cuna para los más pequeños.', 'Wifi,Cocina,Calefacción', 'Aparcamiento gratuito,Cuna', 'Puebla de Sanabria, Zamora', 'Zamora', 5, 5, 95.00, '601234578', 2, TRUE, 3),
('Casa Rural El Mirador', 'ImagenProducto imagenProducto10', 'ImagenSecundaria casarural10secundaria1', 'ImagenSecundaria casarural10secundaria2', 'Casa Rural', 'Disfruta de unas vistas impresionantes en esta casa rural con mirador y vistas a la montaña.', 'Casa rural con mirador y vistas a la montaña, perfecta para relajarse. Déjate sorprender por las impresionantes vistas panorámicas que ofrece nuestro mirador y relájate mientras disfrutas de la belleza natural que te rodea. Equipada con todas las comodidades necesarias, como conexión Wi-Fi gratuita y cocina totalmente equipada, esta casa rural es el lugar ideal para una escapada relajante. Además, podrás disfrutar de servicios como aparcamiento gratuito y acceso a una piscina para refrescarte en los días calurosos.', 'Wifi,Cocina,TV', 'Aparcamiento gratuito,Piscina', 'Anento, Zaragoza', 'Zaragoza', 2, 8, 110.00, '613345689', 4, TRUE, 2);


## INSERTS DE HOTELES
INSERT INTO Alojamientos (nombre, imagen, imagen1, imagen2, tipo, descripcion, descripcionlarga, servicios, prestaciones, localizacion, region, valoracion, capacidad, precio, numTelf, numHabs, habsDisponibles, lavabos) 
VALUES 
('Hotel Rural El Paraíso', 'ImagenProducto imagenProducto11', 'ImagenSecundaria hoteles1secundaria1', 'ImagenSecundaria hoteles1secundaria2', 'Hotel', 'Hotel rural con encanto en plena naturaleza.', 'Hotel rural con encanto en plena naturaleza y vistas panorámicas. Sumérgete en un remanso de paz donde la tranquilidad de la naturaleza se combina con el confort de unas instalaciones cuidadas al detalle. Descubre la magia de despertar cada mañana con el canto de los pájaros y el aroma fresco de la montaña. Déjate seducir por la belleza de los paisajes que rodean este refugio rural, ideales para los amantes del senderismo y la aventura.', 'Cocina,Aire Acondicionado', 'Piscina,Aparcamiento gratuito,Cuna', 'Helechosa de los Montes, Badajoz', 'Badajoz', 5, 15, 70.00, '687624321', 8, TRUE, 1),
('Hotel Sierra Verde', 'ImagenProducto imagenProducto12', 'ImagenSecundaria hoteles2secundaria1', 'ImagenSecundaria hoteles2secundaria2', 'Hotel', 'Hotel boutique en la sierra con diseño moderno.', 'Hotel boutique en la sierra con diseño moderno y servicios exclusivos. Sumérgete en una experiencia de lujo y comodidad en medio de la naturaleza. Cada rincón de este hotel está pensado para ofrecerte una estancia inolvidable, desde su elegante decoración hasta sus servicios de alta gama. Relájate junto a la chimenea en invierno o disfruta del aire puro de la montaña en su amplia terraza. Descubre el equilibrio perfecto entre sofisticación y entorno natural en este oasis de tranquilidad.', 'Cocina,Aire Acondicionado', 'Aparcamiento gratuito,Barbacoa,Chimenea interior', 'Frías, Burgos', 'Burgos', 5, 12, 80.00, '671543210', 6, TRUE, 1),
('Hotel Riaza Montañas', 'ImagenProducto imagenProducto13', 'ImagenSecundaria hoteles3secundaria1', 'ImagenSecundaria hoteles3secundaria2', 'Hotel', 'Hotel de montaña con ambiente tranquilo.', 'Hotel de montaña con ambiente tranquilo y acceso directo a rutas de senderismo. Sumérgete en la serenidad de la montaña y desconecta del estrés diario en este acogedor hotel. Disfruta de largos paseos por la naturaleza y contempla la belleza de los paisajes que te rodean. Con una ubicación privilegiada, este hotel es el punto de partida ideal para explorar las montañas y descubrir su riqueza natural.', 'Wifi,Cocina,Secador de Pelo', 'Piscina,Aparcamiento gratuito,Cuna', 'Riaza, Segovia', 'Segovia', 3, 20, 150.00, '665432119', 10, TRUE, 2),
('Hotel Encanto San Martín', 'ImagenProducto imagenProducto14', 'ImagenSecundaria hoteles4secundaria1', 'ImagenSecundaria hoteles4secundaria2', 'Hotel', 'Hotel en medio del bosque con habitaciones temáticas.', 'Hotel en medio del bosque con habitaciones temáticas y actividades para toda la familia. Sumérgete en un mundo de fantasía en medio de la naturaleza y vive una experiencia única en este encantador hotel. Descubre la magia de sus habitaciones temáticas y disfruta de actividades al aire libre para todas las edades. Con su ambiente acogedor y su entorno natural, este hotel es el destino perfecto para unas vacaciones en familia inolvidables.', 'Cocina,Secadora,TV', 'Piscina,Aparcamiento gratuito,Cuna', 'San Martín de Trevejo, Cáceres', 'Cáceres', 4, 25, 90.00, '611321098', 12, TRUE, 1),
('Hotel Vista al Mar', 'ImagenProducto imagenProducto15', 'ImagenSecundaria hoteles5secundaria1', 'ImagenSecundaria hoteles5secundaria2', 'Hotel', 'Hotel junto al mar con habitaciones luminosas.', 'Hotel junto al mar con habitaciones luminosas y decoración marinera. Disfruta de unas vacaciones junto al mar en este encantador hotel de ambiente marinero. Déjate llevar por la brisa del mar y relájate en sus cómodas habitaciones, diseñadas para proporcionarte el máximo confort. Con su ubicación privilegiada, este hotel es el lugar perfecto para disfrutar del sol y la playa en cualquier época del año.', 'Wifi,Cocina,Aire Acondicionado,Secador de Pelo', 'Piscina,Aparcamiento gratuito,Cuna', 'Fornalutx, Mallorca', 'Mallorca', 2, 30, 100.00, '643212287', 15, TRUE, 1),
('Hotel La Cabaña', 'ImagenProducto imagenProducto16', 'ImagenSecundaria hoteles6secundaria1', 'ImagenSecundaria hoteles6secundaria2', 'Hotel', 'Hotel rural con jardines tropicales.', 'Hotel rural con jardines tropicales y ambiente relajado. Sumérgete en un oasis de tranquilidad en medio de la naturaleza y descubre la belleza de los jardines tropicales que rodean este encantador hotel. Con su ambiente relajado y su atmósfera acogedora, este hotel es el refugio perfecto para aquellos que buscan desconectar del ajetreo de la ciudad y reconectar con la naturaleza.', 'Wifi,Cocina,Aire Acondicionado', 'Piscina,Aparcamiento gratuito,Cuna', 'Cabañaquinta, Asturias', 'Asturias', 1, 18, 160.00, '632109876', 9, TRUE, 1),
('Hotel Lanjarón', 'ImagenProducto imagenProducto17', 'ImagenSecundaria hoteles7secundaria1', 'ImagenSecundaria hoteles7secundaria2', 'Hotel', 'Hotel con encanto en la costa mediterránea.', 'Hotel con encanto en la costa mediterránea y vistas al mar. Déjate seducir por la magia del Mediterráneo y disfruta de unas vistas impresionantes desde este encantador hotel. Con su ambiente acogedor y su decoración elegante, este hotel es el lugar perfecto para relajarse y disfrutar de la belleza del mar. Descubre la hospitalidad mediterránea y déjate mimar por un servicio impecable en un entorno único.', 'Wifi,Cocina,Aire Acondicionado,Secador de Pelo', 'Piscina,Aparcamiento gratuito,Cuna', 'Lanjarón, Granada', 'Granada', 2, 22, 85.00, '621098555', 11, TRUE, 1),
('Hotel Almonaster', 'ImagenProducto imagenProducto18', 'ImagenSecundaria hoteles8secundaria1', 'ImagenSecundaria hoteles8secundaria2', 'Hotel', 'Hotel oasis en pleno desierto con arquitectura tradicional.', 'Hotel oasis en pleno desierto con arquitectura tradicional y piscina. Sumérgete en un oasis de tranquilidad en medio del desierto y descubre la magia de este encantador hotel. Con su arquitectura tradicional y su exuberante vegetación, este hotel te transportará a un mundo de ensueño en pleno corazón del desierto. Relájate junto a su piscina oasis y disfruta de una experiencia única bajo el cielo estrellado del desierto.', 'Wifi,Cocina,Aire Acondicionado', 'Piscina,Aparcamiento gratuito', 'Almonaster la Real, Huelva', 'Huelva', 4, 16, 70.00, '666987654', 8, TRUE, 1),
('Hotel Rural Los Olivos en Lleida', 'ImagenProducto imagenProducto19', 'ImagenSecundaria hoteles9secundaria1', 'ImagenSecundaria hoteles9secundaria2', 'Hotel', 'Hotel rural entre campos de olivos en Lleida.', 'Sumérgete en la tranquilidad de la naturaleza en el Hotel Rural Los Olivos en Lleida. Rodeado de campos de olivos, este encantador hotel ofrece una escapada rural perfecta. Disfruta de la serenidad del entorno y relájate en sus cómodas instalaciones después de un día explorando la región. Con una variedad de servicios disponibles, como conexión Wi-Fi gratuita y piscina al aire libre, tu estancia será inolvidable.', 'Cocina', 'Aparcamiento gratuito', 'Ivars Urgell, Lleida', 'Lleida', 5, 20, 50.00, '609855543', 10, TRUE, 1),
('Hotel Guadalupe', 'ImagenProducto imagenProducto20', 'ImagenSecundaria hoteles10secundaria1', 'ImagenSecundaria hoteles10secundaria2', 'Hotel', 'Hotel con encanto en Guadalupe, ideal para turismo rural y actividades al aire libre.', 'Hotel con encanto en Guadalupe, ideal para turismo rural y actividades al aire libre. Sumérgete en la belleza del norte y descubre la magia de este encantador hotel. Con su ubicación privilegiada y su ambiente acogedor, este hotel es el punto de partida perfecto para explorar la belleza natural del norte y disfrutar de actividades al aire libre. Descubre la hospitalidad del norte y déjate seducir por la calidez de su gente en este encantador hotel.', 'Wifi,Cocina,Aire Acondicionado', 'Piscina,Aparcamiento gratuito,Cuna', 'Guadalupe, Cáceres', 'Cáceres', 5, 20, 80.00, '698777432', 10, TRUE, 1);


## INSERTS DE APARTAMENTOS
INSERT INTO Alojamientos (nombre, imagen, imagen1, imagen2, tipo, descripcion, descripcionlarga, servicios, prestaciones, localizacion, region, valoracion, capacidad, precio, numTelf, numHabs, habsDisponibles, lavabos) 
VALUES 
('Apartamento Costa de Ayllón', 'ImagenProducto imagenProducto21', 'ImagenSecundaria apartamento1secundaria1', 'ImagenSecundaria apartamento1secundaria2', 'Apartamento', 'Moderno apartamento con acceso a la playa en Ayllón.', 'Moderno apartamento con vistas al mar y acceso directo a la playa en Ayllón. Disfruta de la comodidad de un hogar junto al mar en este moderno apartamento. Con su ubicación privilegiada y su acceso directo a la playa, este apartamento es el lugar perfecto para relajarse y disfrutar del sol y la brisa del mar. Déjate seducir por las impresionantes vistas al mar desde su terraza y descubre la belleza de la costa desde la comodidad de tu propio espacio.', 'Cocina,Aire Acondicionado,Secador de Pelo', 'Piscina,Aparcamiento gratuito,Barbacoa', 'Ayllón, Segovia', 'Segovia', 5, 4, 77.00, '623488789', 2, TRUE, 1),
('Apartamento Montañas de Rubielos', 'ImagenProducto imagenProducto22', 'ImagenSecundaria apartamento2secundaria1', 'ImagenSecundaria apartamento2secundaria2', 'Apartamento', 'Acogedor apartamento en las montañas con chimenea y rutas de senderismo cercanas en Rubielos de Mora.', 'Apartamento acogedor en las montañas con chimenea y rutas de senderismo cercanas en Rubielos de Mora. Sumérgete en la belleza de la montaña y disfruta de una estancia acogedora en este encantador apartamento. Con su chimenea y su ambiente cálido, este apartamento es el refugio perfecto para desconectar del mundo y reconectar con la naturaleza. Descubre las rutas de senderismo cercanas y déjate sorprender por la belleza de los paisajes que te rodean.', 'Wifi,Cocina,Calefacción', 'Cuna,Aparcamiento gratuito,Barbacoa', 'Rubielos de Mora, Teruel', 'Teruel', 5, 6, 100.00, '634567880', 3, TRUE, 1),
('Apartamento Castillo de Miranda', 'ImagenProducto imagenProducto23', 'ImagenSecundaria apartamento3secundaria1', 'ImagenSecundaria apartamento3secundaria2', 'Apartamento', 'Apartamento en el corazón del centro histórico con terraza privada.', 'Apartamento en el corazón del centro histórico con terraza privada y vistas panorámicas en Miranda del Castañar. Descubre el encanto de esta ciudad medieval desde este exclusivo apartamento en el corazón del centro urbano. Con su terraza privada y sus vistas panorámicas, este apartamento te ofrece una experiencia única para disfrutar de la vida urbana en su máxima expresión. Déjate seducir por la belleza del Castillo de Miranda y la atmósfera medieval desde la comodidad de tu propio espacio.', 'Cocina,Aire Acondicionado', 'Aparcamiento gratuito,Chimenea interior', 'Miranda del Castañar, Salamanca', 'Salamanca', 4, 3, 60.00, '645678901', 2, TRUE, 2),
('Apartamento Playa de Beget', 'ImagenProducto imagenProducto24', 'ImagenSecundaria apartamento4secundaria1', 'ImagenSecundaria apartamento4secundaria2', 'Apartamento', 'Apartamento frente al mar con encantadora decoración marinera.', 'Apartamento frente al mar con encantadora decoración marinera y acceso directo a la playa en Beget. Sumérgete en la magia del mar y disfruta de unas vacaciones junto al mar en este encantador apartamento. Con su decoración marinera y su acceso directo a la playa, este apartamento te ofrece todo lo necesario para una estancia inolvidable frente al mar. Déjate llevar por la brisa del mar y relájate en este oasis de tranquilidad en la costa.', 'Wifi,Cocina,Aire Acondicionado', 'Piscina,Aparcamiento gratuito,Cuna', 'Beget, Girona', 'Girona', 4, 4, 60.00, '656789712', 2, TRUE, 1),
('Apartamento Sierra de Linares', 'ImagenProducto imagenProducto25', 'ImagenSecundaria apartamento5secundaria1', 'ImagenSecundaria apartamento5secundaria2', 'Apartamento', 'Apartamento en la montaña con vistas espectaculares y tranquilidad absoluta.', 'Apartamento en la montaña con vistas espectaculares y ambiente tranquilo en Linares de Mora. Disfruta de unas vacaciones en plena naturaleza y descubre la belleza de la montaña desde este acogedor apartamento. Con sus vistas espectaculares y su ambiente tranquilo, este apartamento te ofrece el espacio perfecto para desconectar del mundo y reconectar con la naturaleza. Relájate en su terraza y contempla la belleza de los paisajes que te rodean.', 'Cocina,Calefacción', 'Cuna,Aparcamiento gratuito,Barbacoa', 'Linares de Mora, Teruel', 'Teruel', 2, 5, 74.00, '666890123', 3, TRUE, 1),
('Apartamento Río Liera', 'ImagenProducto imagenProducto26', 'ImagenSecundaria apartamento6secundaria1', 'ImagenSecundaria apartamento6secundaria2', 'Apartamento', 'Apartamento junto al río con jardín privado y actividades acuáticas.', 'Descubre un refugio junto al río en este encantador apartamento en Lierganes. Con su jardín privado y actividades acuáticas, te ofrece la oportunidad de vivir una experiencia inolvidable en plena naturaleza. Relájate junto al río y déjate llevar por el sonido de sus aguas mientras disfrutas de la tranquilidad del entorno.', 'Wifi,Cocina,Aire Acondicionado', 'Aparcamiento gratuito,Barbacoa,Chimenea interior', 'Lierganes, Cantabria', 'Cantabria', 5, 4, 85.00, '678921234', 2, TRUE, 1),
('Apartamento Hervás Deluxe', 'ImagenProducto imagenProducto27', 'ImagenSecundaria apartamento7secundaria1', 'ImagenSecundaria apartamento7secundaria2', 'Apartamento', 'Apartamento de lujo en el centro de la ciudad.', 'Disfruta de una estancia de lujo en pleno corazón de Hervás en este exclusivo apartamento. Con su diseño moderno y sus servicios exclusivos, te ofrece todo lo necesario para una estancia inolvidable en la ciudad. Relájate en su piscina y déjate llevar por el encanto del centro urbano desde la comodidad de tu propio espacio.', 'Cocina,Aire Acondicionado,Secador de Pelo', 'Piscina,Aparcamiento gratuito,Chimenea interior', 'Hervás, Cáceres', 'Cáceres', 3, 3, 90.00, '689012345', 2, TRUE, 2),
('Apartamento Daroca Verde', 'ImagenProducto imagenProducto28', 'ImagenSecundaria apartamento8secundaria1', 'ImagenSecundaria apartamento8secundaria2', 'Apartamento', 'Apartamento en la naturaleza con vistas a las montañas.', 'Descubre la belleza de las montañas desde este encantador apartamento en plena naturaleza. Con sus vistas panorámicas y senderos para caminatas, te ofrece la oportunidad de explorar la belleza natural que te rodea. Relájate en su terraza y déjate seducir por la calma y la tranquilidad del entorno.', 'Wifi,Cocina,Calefacción', 'Aparcamiento gratuito,Cuna,Barbacoa', 'Daroca, Zaragoza', 'Zaragoza', 2, 5, 45.00, '690123116', 3, TRUE, 1),
('Apartamento Sepúlveda Marina', 'ImagenProducto imagenProducto29', 'ImagenSecundaria apartamento9secundaria1', 'ImagenSecundaria apartamento9secundaria2', 'Apartamento', 'Apartamento junto al mar con terraza y acceso privado a la playa.', 'Sumérgete en la belleza del mar y disfruta de unas vacaciones junto al mar en este encantador apartamento en Sepúlveda. Con su terraza privada y su acceso privado a la playa, te ofrece todo lo necesario para una estancia inolvidable. Relájate en su terraza y déjate llevar por el sonido de las olas mientras disfrutas del sol y la brisa marina.', 'Cocina,Aire Acondicionado', 'Piscina,Aparcamiento gratuito,Chimenea interior', 'Sepúlveda, Segovia', 'Segovia', 1, 4, 30.00, '613234567', 2, TRUE, 2),
('Apartamento Ainsa Bosque Verde', 'ImagenProducto imagenProducto30', 'ImagenSecundaria apartamento10secundaria1', 'ImagenSecundaria apartamento10secundaria2', 'Apartamento', 'Apartamento con encanto rural y vistas al bosque.', 'Sumérgete en la tranquilidad de la naturaleza y disfruta de una estancia relajante en este encantador apartamento rural en Ainsa. Con sus vistas al bosque y su ambiente tranquilo, te ofrece el lugar perfecto para desconectar del estrés diario y reconectar con la naturaleza. Relájate en su terraza y déjate llevar por la calma del entorno.', 'Wifi,Cocina,Calefacción', 'Aparcamiento gratuito,Barbacoa,Chimenea interior', 'Ainsa, Huesca', 'Huesca', 5, 5, 55.00, '612388678', 3, TRUE, 1);



# INSERTS DE CAMPINGS
INSERT INTO Alojamientos (nombre, imagen, imagen1, imagen2, tipo, descripcion, descripcionlarga, servicios, prestaciones, localizacion, region, valoracion, capacidad, precio, numTelf, numHabs, habsDisponibles, lavabos) 
VALUES 
('Camping La Alberca Verde', 'ImagenProducto imagenProducto31', 'ImagenSecundaria camping1secundaria1', 'ImagenSecundaria camping1secundaria2', 'Camping', 'Camping en plena naturaleza con parcelas y bungalows.', 'Disfruta de la tranquilidad de la naturaleza y desconecta del estrés diario en este acogedor camping en La Alberca. Con sus amplias parcelas y cómodos bungalows, este camping es el destino perfecto para unas vacaciones en familia o con amigos. Disfruta de actividades al aire libre y relájate junto a la piscina en un entorno natural incomparable.', 'Cocina', 'Piscina,Aparcamiento gratuito,Barbacoa', 'La Alberca, Salamanca', 'Salamanca', 5, 50, 20.00, '623996780', 25, TRUE, 1),
('Camping Alfaques', 'ImagenProducto imagenProducto32', 'ImagenSecundaria camping2secundaria1', 'ImagenSecundaria camping2secundaria2', 'Camping', 'Camping rural junto al río en Tarragona.', 'Disfruta de la serenidad de la vida al aire libre en este encantador camping ubicado en las proximidades del río en Tarragona. Sumérgete en la belleza natural de la región y relájate junto al agua mientras disfrutas de actividades al aire libre como pesca y paseos en kayak. Con su ambiente tranquilo y su conexión con la naturaleza, este camping es el refugio perfecto para escapar del ajetreo de la ciudad y reconectar con el entorno rural.', 'Cocina', 'Aparcamiento gratuito,Piscina,Cuna', 'Alcanar, Tarragona', 'Tarragona', 4, 60, 22.00, '634567091', 30, TRUE, 3),
('Camping Río Oja', 'ImagenProducto imagenProducto33', 'ImagenSecundaria camping3secundaria1', 'ImagenSecundaria camping3secundaria2', 'Camping', 'Camping junto al río con acceso directo a la playa y animación.', 'Disfruta de unas vacaciones en plena naturaleza en este acogedor camping en Ezcaray, donde la diversión está garantizada. Con acceso directo al río y un programa de animación para todas las edades, este camping es el destino perfecto para unas vacaciones en familia o con amigos. Relájate junto al río y disfruta de la brisa del aire fresco en un entorno natural incomparable.', 'Cocina', 'Piscina,Aparcamiento gratuito,Cuna', 'Ezcaray, La Rioja', 'La Rioja', 3, 80, 25.00, '645678233', 40, TRUE, 3),
('Camping Puig Roig', 'ImagenProducto imagenProducto34', 'ImagenSecundaria camping4secundaria1', 'ImagenSecundaria camping4secundaria2', 'Camping', 'Camping en la montaña con rutas de senderismo y tranquilidad.', 'Disfruta de unas vacaciones en plena naturaleza en el Camping Puig Roig, ubicado en Morella, Castellón. Sumérgete en la belleza de la montaña y desconecta del ajetreo de la ciudad en este acogedor camping. Con sus rutas de senderismo y su ambiente tranquilo, este camping es el destino perfecto para los amantes de la naturaleza y la aventura. Disfruta de la tranquilidad y la paz de la montaña en un entorno natural incomparable.', 'Cocina', 'Aparcamiento gratuito,Barbacoa', 'Morella, Castellón', 'Castellón', 4, 70, 23.00, '656789344', 35, TRUE, 3),
('Camping Río Guadalquivir', 'ImagenProducto imagenProducto35', 'ImagenSecundaria camping5secundaria1', 'ImagenSecundaria camping5secundaria2', 'Camping', 'Camping junto al río con actividades acuáticas y naturaleza.', 'Disfruta de unas vacaciones únicas en el Camping Río Guadalquivir, ubicado en Carmona, Sevilla. Este encantador camping se encuentra junto al río, ofreciendo actividades acuáticas y experiencias en plena naturaleza. Ideal para unas vacaciones activas y divertidas, podrás relajarte junto al río y disfrutar de la frescura del agua en un entorno natural incomparable.', 'Cocina', 'Piscina,Aparcamiento gratuito,Barbacoa', 'Carmona, Sevilla', 'Sevilla', 3, 45, 18.00, '667890455', 20, TRUE, 3),
('Camping Dunas de Peñíscola', 'ImagenProducto imagenProducto36', 'ImagenSecundaria camping6secundaria1', 'ImagenSecundaria camping6secundaria2', 'Camping', 'Camping junto a las dunas con instalaciones modernas y ambiente tranquilo.', 'Descubre la belleza de Peñíscola en el Camping Dunas de Peñíscola, ubicado en Castellón. Este camping se encuentra junto a las dunas, ofreciendo instalaciones modernas y un ambiente tranquilo. Sumérgete en un oasis de tranquilidad en medio del paisaje dunar y disfruta de unas vacaciones únicas en este encantador camping. Relájate bajo el cielo estrellado y disfruta de la paz y la serenidad del entorno.', 'Wifi,Cocina', 'Piscina,Aparcamiento gratuito,Cuna', 'Peñíscola, Castellón', 'Castellón', 4, 55, 21.00, '678901566', 28, TRUE, 3),
('Camping Pedraza Mar', 'ImagenProducto imagenProducto37', 'ImagenSecundaria camping7secundaria1', 'ImagenSecundaria camping7secundaria2', 'Camping', 'Camping junto a la playa con deportes acuáticos y animación para niños.', 'Disfruta de unas vacaciones junto al mar en el Camping Pedraza Mar, ubicado en Pedraza, Segovia. Este encantador camping ofrece deportes acuáticos y un programa de animación para niños, asegurando diversión para toda la familia. Relájate bajo el sol y disfruta de la brisa del mar en un entorno natural incomparable.', 'Wifi,Cocina', 'Piscina,Aparcamiento gratuito,Cuna', 'Pedraza, Segovia', 'Segovia', 2, 90, 28.00, '689012677', 45, TRUE, 3),
('Camping Combarro Verde', 'ImagenProducto imagenProducto38', 'ImagenSecundaria camping8secundaria1', 'ImagenSecundaria camping8secundaria2', 'Camping', 'Camping en el centro de la ciudad con parcelas y bungalows.', 'Descubre la comodidad de acampar en pleno centro urbano en el Camping Combarro Verde, ubicado en Combarro, Pontevedra. Este moderno camping ofrece amplias parcelas y cómodos bungalows, proporcionando la combinación perfecta de naturaleza y ciudad. Disfruta de la vida urbana y de la tranquilidad de la naturaleza en un mismo lugar.', 'Wifi,Cocina', 'Aparcamiento gratuito,Piscina', 'Combarro, Pontevedra', 'Pontevedra', 5, 40, 20.00, '690123788', 20, TRUE, 3),
('Camping Alburquerque Estrellas', 'ImagenProducto imagenProducto39', 'ImagenSecundaria camping9secundaria1', 'ImagenSecundaria camping9secundaria2', 'Camping', 'Camping en plena naturaleza con actividades de aventura y observación de estrellas.', 'Sumérgete en la belleza de la naturaleza y descubre la magia del cielo estrellado en el Camping Alburquerque Estrellas, ubicado en Alburquerque, Badajoz. Con actividades de aventura y observación de estrellas, este camping es el destino perfecto para los amantes de la naturaleza y la astronomía. Relájate bajo las estrellas y disfruta de la belleza del universo en un entorno natural incomparable.', 'Cocina', 'Piscina,Aparcamiento gratuito,Barbacoa', 'Alburquerque, Badajoz', 'Badajoz', 4, 65, 24.00, '601234899', 32, TRUE, 3),
('Camping Cazorla Bahía', 'ImagenProducto imagenProducto40', 'ImagenSecundaria camping10secundaria1', 'ImagenSecundaria camping10secundaria2', 'Camping', 'Camping junto a la bahía con vistas al mar y ambiente familiar.', 'Disfruta de unas vacaciones junto al mar en el Camping Cazorla Bahía, ubicado en Cazorla, Jaén, donde la tranquilidad y el ambiente familiar están garantizados. Con vistas al mar y un ambiente acogedor, este camping es el destino perfecto para unas vacaciones en familia o con amigos. Relájate bajo el sol y disfruta de la brisa del mar en un entorno natural incomparable.', 'Cocina', 'Piscina,Aparcamiento gratuito,Cuna', 'Cazorla, Jaén', 'Jaén', 3, 75, 26.00, '612345910', 38, TRUE, 3);

# INSERTS DE ACTIVIDADES AVENTURA
INSERT INTO Actividades (nombre, imagen, imagen1, imagen2, localizacion, region, precio, duracion, dificultad, numTelf, tipo, categoria, descripcion, descripcionlarga, fechaInicio, hora, plazasDisponibles) 
VALUES 
('Senderismo en Ronda - Málaga', 'ImagenProducto imagenProducto41', 'ImagenSecundaria aventura1secundaria1', 'ImagenSecundaria aventura1secundaria2', 'Ronda, Málaga', 'Málaga', 20.00, 180, 'Media', '623456789', 'Aventura', 'Senderismo', 'Explora la naturaleza de Ronda - Málaga.', 'Embárcate en una emocionante caminata guiada por los impresionantes senderos de Ronda - Málaga. Sumérgete en la belleza natural de esta región montañosa mientras exploras paisajes vírgenes y te desconectas del bullicio urbano.', '2024-06-15', '10:00:00', 15),
('Ruta en bicicleta por Berlanga de Duero - Soria', 'ImagenProducto imagenProducto42', 'ImagenSecundaria aventura2secundaria1', 'ImagenSecundaria aventura2secundaria2', 'Berlanga de Duero, Soria', 'Soria', 25.00, 150, 'Media', '645678901', 'Aventura', 'Ciclismo de montaña', 'Explora la Sierra de Grazalema en bicicleta.', 'Embárcate en una emocionante ruta en bicicleta por Berlanga de Duero - Soria, recorriendo sus senderos y disfrutando de sus paisajes.', '2024-06-17', '09:00:00', 18),
('Escalada en roca en Frigiliana', 'ImagenProducto imagenProducto43', 'ImagenSecundaria aventura3secundaria1', 'ImagenSecundaria aventura3secundaria2', 'Frigiliana, Málaga', 'Málaga', 70.00, 180, 'Media', '678901234', 'Aventura', 'Escalada en roca', 'Desafía tus límites con la escalada en roca en Frigiliana - Málaga.', 'Sumérgete en la emoción de la escalada en roca en los impresionantes paisajes de Frigiliana - Málaga. Con la guía de expertos escaladores, tendrás la oportunidad de desafiar tus habilidades y conquistar nuevas alturas mientras disfrutas de las vistas panorámicas y la naturaleza virgen que rodea este destino de aventura.', '2024-06-20', '07:00:00', 10),
('Ecoturismo en las Rías Baixas', 'ImagenProducto imagenProducto44', 'ImagenSecundaria aventura4secundaria1', 'ImagenSecundaria aventura4secundaria2', 'Pontedeume, A Coruña', 'A Coruña', 25.00, 180, 'Baja', '689000345', 'Aventura', 'Ecoturismo', 'Experiencia de ecoturismo en las Rías Baixas.', 'Sumérgete en la belleza natural de las Rías Baixas con una experiencia de ecoturismo que te llevará a explorar sus costas, playas y aldeas pintorescas.', '2024-06-21', '11:00:00', 15),
('Rutas a Caballo en Mojácar, Almería', 'ImagenProducto imagenProducto45', 'ImagenSecundaria aventura5secundaria1', 'ImagenSecundaria aventura5secundaria2', 'Mojácar, Almería', 'Almería', 45.00, 120, 'Media', '690123456', 'Aventura', 'Rutas a caballo', 'Aventura a caballo por Mojácar, Almería.', 'Embárcate en una emocionante aventura a caballo por los impresionantes paisajes de Mojácar, Almería, donde podrás explorar su flora y fauna únicas mientras disfrutas de una experiencia inolvidable.', '2024-06-22', '09:30:00', 8),
('Observación Astronómica en Almagro, Ciudad Real', 'ImagenProducto imagenProducto46', 'ImagenSecundaria aventura6secundaria1', 'ImagenSecundaria aventura6secundaria2', 'Almagro, Ciudad Real', 'Ciudad Real', 30.00, 180, 'Alta', '901234567', 'Aventura', 'Observación astronómica', 'Exploración del cielo nocturno de Almagro, Ciudad Real.', 'Descubre el cielo nocturno de Almagro, Ciudad Real, y maravíllate con las maravillas del universo mientras exploras los alrededores con la guía de un experto en astronomía.', '2024-06-23', '22:00:00', 12),
('Avistamiento de Aves en Tossa de Mar', 'ImagenProducto imagenProducto47', 'ImagenSecundaria aventura7secundaria1', 'ImagenSecundaria aventura7secundaria2', 'Tossa de Mar, Girona', 'Girona', 10.00, 180, 'Media', '610987654', 'Aventura', 'Avistamiento de aves', 'Excursión de avistamiento de aves en Tossa de Mar.', 'Únete a una emocionante excursión de avistamiento de aves en el hermoso entorno de Tossa de Mar, Girona, y descubre la increíble diversidad de avifauna que habita en la zona.', '2024-06-24', '08:30:00', 12),
('Descenso en Kayak por el Río Guadiana', 'ImagenProducto imagenProducto48', 'ImagenSecundaria aventura8secundaria1', 'ImagenSecundaria aventura8secundaria2', 'Aracena, Huelva', 'Huelva', 35.00, 150, 'Media', '621098765', 'Aventura', 'Senderismo', 'Aventura en kayak por el Río Guadiana', 'Embárcate en una emocionante aventura en kayak por el hermoso Río Guadiana, en Aracena, Huelva. Disfruta de la serenidad del agua mientras exploras los paisajes naturales de la zona y descubres la belleza de sus riberas.', '2024-06-25', '10:00:00', 10),
('Senderismo en Baeza, Jaén', 'ImagenProducto imagenProducto49', 'ImagenSecundaria aventura9secundaria1', 'ImagenSecundaria aventura9secundaria2', 'Baeza, Jaén', 'Jaén', 25.00, 120, 'Media', '632109876', 'Aventura', 'Senderismo', 'Excursión de senderismo en Baeza, Jaén', 'Embárcate en una emocionante excursión de senderismo por los hermosos paisajes de Baeza, Jaén, explorando sus senderos, bosques y cascadas.', '2024-06-26', '09:00:00', 20),
('Escalada en Mondoñedo, Lugo', 'ImagenProducto imagenProducto50', 'ImagenSecundaria aventura10secundaria1', 'ImagenSecundaria aventura10secundaria2', 'Mondoñedo, Lugo', 'Lugo', 40.00, 180, 'Alta', '643210987', 'Aventura', 'Ecoturismo', 'Aventura de escalada en Mondoñedo, Lugo', 'Desafía tus límites con una emocionante sesión de escalada en las imponentes montañas de Mondoñedo, Lugo, donde podrás disfrutar de vistas panorámicas y experimentar la adrenalina pura mientras escalas.', '2024-06-27', '12:00:00', 8);


# INSERTS DE ACTIVIDADES DE VISITAR
INSERT INTO Actividades (nombre, imagen, imagen1, imagen2, localizacion, region, precio, duracion, dificultad, numTelf, tipo, categoria, descripcion, descripcionlarga, fechaInicio, hora, plazasDisponibles) 
VALUES 
('Visita a la Ruta de Onda, Castellón', 'ImagenProducto imagenProducto51', 'ImagenSecundaria visitar1secundaria1', 'ImagenSecundaria visitar1secundaria2', 'Onda, Castellón', 'Castellón', 25.00, 180, 'Media', '623456780', 'Visitar', 'Senderismo', 'Explora la Ruta de Onda, Castellón', 'Embárcate en una aventura para explorar la espectacular Ruta de Onda, Castellón. Este sendero escénico serpentea a lo largo de un desfiladero profundo en los Picos de Europa, ofreciendo impresionantes vistas de montañas y valles.', '2024-06-15', '09:00:00', 20),
('Tour por Antequera, Málaga', 'ImagenProducto imagenProducto52', 'ImagenSecundaria visitar2secundaria1', 'ImagenSecundaria visitar2secundaria2', 'Antequera, Málaga', 'Málaga', 30.00, 240, 'Media', '634567891', 'Visitar', 'Turismo cultural', 'Explora Antequera, Málaga', 'Embárcate en un encantador tour por Antequera, Málaga, explorando sus estrechas calles empedradas, casas encaladas y disfrutando de la auténtica vida rural de esta pintoresca localidad andaluza.', '2024-06-16', '10:30:00', 15),
('Visita a Buitrago del Lozoya, Madrid', 'ImagenProducto imagenProducto53', 'ImagenSecundaria visitar3secundaria1', 'ImagenSecundaria visitar3secundaria2', 'Buitrago del Lozoya, Madrid', 'Madrid', 90.00, 180, 'Baja', '645678912', 'Visitar', 'Turismo cultural', 'Explora Buitrago del Lozoya, Madrid', 'Embárcate en un recorrido por Buitrago del Lozoya, Madrid, donde el tiempo parece detenerse entre sus acogedoras aldeas, disfrutando de su arquitectura tradicional, paisajes montañosos y la hospitalidad de sus habitantes.', '2024-06-17', '14:00:00', 25),
('Ruta por Guadix, Granada', 'ImagenProducto imagenProducto54', 'ImagenSecundaria visitar4secundaria1', 'ImagenSecundaria visitar4secundaria2', 'Guadix, Granada', 'Granada', 35.00, 150, 'Media', '656789123', 'Visitar', 'Turismo cultural', 'Explora Guadix, Granada', 'Embárcate en una ruta guiada por Guadix, Granada, que te llevará a través de hermosos paisajes de viñedos, donde podrás aprender sobre el proceso de elaboración del vino y degustar algunos de los mejores caldos de la región.', '2024-06-18', '11:00:00', 12),
('Visita a Alhama de Granada, Granada', 'ImagenProducto imagenProducto55', 'ImagenSecundaria visitar5secundaria1', 'ImagenSecundaria visitar5secundaria2', 'Alhama de Granada, Granada', 'Granada', 55.00, 180, 'Media', '667891234', 'Visitar', 'Turismo cultural', 'Explora Alhama de Granada, Granada', 'Embárcate en una visita a Alhama de Granada, Granada, sumergiéndote en su historia medieval con encantadores pueblos medievales, donde podrás admirar castillos, iglesias románicas y calles empedradas llenas de encanto.', '2024-06-19', '09:00:00', 20),
('Excursión a Belmonte, Cuenca', 'ImagenProducto imagenProducto56', 'ImagenSecundaria visitar6secundaria1', 'ImagenSecundaria visitar6secundaria2', 'Belmonte, Cuenca', 'Cuenca', 40.00, 240, 'Media', '678912345', 'Visitar', 'Turismo cultural', 'Explora Belmonte, Cuenca', 'Embárcate en una emocionante excursión a Belmonte, Cuenca, donde podrás descubrir la belleza natural de la región con sus parques naturales. Explora paisajes montañosos, valles verdes y maravillas geológicas.', '2024-06-20', '08:30:00', 18),
('Tour por los Faros de Camariñas, A Coruña', 'ImagenProducto imagenProducto57', 'ImagenSecundaria visitar7secundaria1', 'ImagenSecundaria visitar7secundaria2', 'Camariñas, A Coruña', 'A Coruña', 30.00, 180, 'Media', '689123456', 'Visitar', 'Turismo cultural', 'Explora los Faros de Camariñas, A Coruña', 'Embárcate en un fascinante tour por los faros de Camariñas, A Coruña, donde podrás recorrer la historia y la belleza de estas emblemáticas estructuras costeras. Descubre la fascinante historia marítima de la región mientras admiras los faros bien conservados y aprendes sobre sus intrincadas leyendas.', '2024-06-21', '10:00:00', 20),
('Visita a Puebla de Don Fadrique, Granada', 'ImagenProducto imagenProducto58', 'ImagenSecundaria visitar8secundaria1', 'ImagenSecundaria visitar8secundaria2', 'Puebla de Don Fadrique, Granada', 'Granada', 45.00, 180, 'Media', '691234567', 'Visitar', 'Turismo cultural', 'Explora Puebla de Don Fadrique, Granada', 'Embárcate en una visita a Puebla de Don Fadrique, Granada, donde podrás explorar los hermosos parques naturales de Galicia. Disfruta de bosques frondosos, cascadas impresionantes y una gran diversidad de flora y fauna en un entorno natural único.', '2024-06-22', '09:00:00', 15),
('Ruta por Sanlúcar de Guadiana, Huelva', 'ImagenProducto imagenProducto59', 'ImagenSecundaria visitar9secundaria1', 'ImagenSecundaria visitar9secundaria2', 'Sanlúcar de Guadiana, Huelva', 'Huelva', 30.00, 180, 'Media', '912345678', 'Visitar', 'Turismo cultural', 'Explora Sanlúcar de Guadiana, Huelva', 'Embárcate en una ruta por Sanlúcar de Guadiana, Huelva, donde podrás descubrir la encantadora Costa Brava con sus pintorescos pueblos pesqueros. Disfruta de hermosas playas, deliciosos mariscos y el encanto marinero de la región.', '2024-06-23', '11:00:00', 18),
('Tour por las Haciendas y Cortijos de Valdepeñas', 'ImagenProducto imagenProducto60', 'ImagenSecundaria visitar10secundaria1', 'ImagenSecundaria visitar10secundaria2', 'Valdepeñas, Ciudad Real', 'Ciudad Real', 65.00, 240, 'Media', '987654321', 'Visitar', 'Turismo cultural', 'Explora Valdepeñas, Ciudad Real', 'Embárcate en un tour por las majestuosas haciendas y cortijos de Valdepeñas, Ciudad Real, donde podrás sumergirte en la historia y la arquitectura andaluzas. Conoce la vida en el campo y disfruta de hermosos paisajes mientras exploras esta encantadora región.', '2024-06-24', '10:30:00', 20);

## INSERTS DE ACTIVIDADES DE ANIMALES
INSERT INTO Actividades (nombre, imagen, imagen1, imagen2, localizacion, region, precio, duracion, dificultad, numTelf, tipo, categoria, descripcion, descripcionlarga, fechaInicio, hora, plazasDisponibles) 
VALUES 
('Ruta de Avistamiento de Aves en Olite', 'ImagenProducto imagenProducto61', 'ImagenSecundaria animales1secundaria1', 'ImagenSecundaria animales1secundaria2', 'Olite, Navarra', 'Navarra', 20.00, 180, 'Baja', '625456789', 'Animales', 'Avistamiento de aves', 'Embárcate en una ruta de avistamiento de aves por los hermosos paisajes de Olite, Navarra.', 'Embárcate en una ruta de avistamiento de aves por los hermosos paisajes de Olite, Navarra, donde podrás observar una gran variedad de especies en su entorno natural.', '2024-07-01', '10:00:00', 15),
('Visita al Centro de Conservación de la Fauna Silvestre en Xàtiva', 'ImagenProducto imagenProducto62', 'ImagenSecundaria animales2secundaria1', 'ImagenSecundaria animales2secundaria2', 'Xàtiva, Valencia', 'Valencia', 35.00, 180, 'Media', '634560890', 'Animales', 'Fotografía de naturaleza', 'Explora el trabajo de conservación de la fauna silvestre en el Centro de Conservación de Xàtiva.', 'Explora el trabajo de conservación de la fauna silvestre en el Centro de Conservación de Xàtiva, donde podrás aprender sobre la protección de especies locales en un entorno rural.', '2024-07-02', '10:00:00', 20),
('Safari Fotográfico en la Reserva Natural de las Marismas de Santo Domingo de la Calzada', 'ImagenProducto imagenProducto63', 'ImagenSecundaria animales3secundaria1', 'ImagenSecundaria animales3secundaria2', 'Santo Domingo de la Calzada, La Rioja', 'La Rioja', 40.00, 180, 'Media', '645478901', 'Animales', 'Fotografía de naturaleza', 'Únete a un emocionante safari fotográfico en la Reserva Natural de las Marismas de Santo Domingo de la Calzada.', 'Únete a un emocionante safari fotográfico en la Reserva Natural de las Marismas de Santo Domingo de la Calzada, donde podrás capturar imágenes de la diversa vida salvaje en un entorno rural protegido.', '2024-07-03', '10:00:00', 12),
('Avistamiento de Aves en los Bosques de Tui', 'ImagenProducto imagenProducto64', 'ImagenSecundaria animales4secundaria1', 'ImagenSecundaria animales4secundaria2', 'Tui, Pontevedra', 'Pontevedra', 45.00, 180, 'Alta', '656781012', 'Animales', 'Ecoturismo', 'Experimenta la emoción de avistar aves en libertad en los bosques de Tui.', 'Experimenta la emoción de avistar aves en libertad en los bosques de Tui, en una excursión guiada por expertos en vida silvestre en la España vacía.', '2024-07-04', '10:00:00', 18),
('Visita a la Reserva Natural en Navalcarnero', 'ImagenProducto imagenProducto65', 'ImagenSecundaria animales5secundaria1', 'ImagenSecundaria animales5secundaria2', 'Navalcarnero, Madrid', 'Madrid', 30.00, 150, 'Baja', '667190123', 'Animales', 'Ecoturismo', 'Descubre la biodiversidad en la Reserva Natural de Navalcarnero.', 'Explora la Reserva Natural de Navalcarnero con un paseo guiado, donde podrás observar la flora y fauna local en un entorno natural protegido.', '2024-07-05', '10:00:00', 15),
('Visita al Centro de Recuperación de Fauna Silvestre en Chinchón', 'ImagenProducto imagenProducto66', 'ImagenSecundaria animales6secundaria1', 'ImagenSecundaria animales6secundaria2', 'Chinchón, Madrid', 'Madrid', 20.00, 120, 'Baja', '618901234', 'Animales', 'Fotografía de naturaleza', 'Explora el trabajo de conservación de la fauna silvestre en el Centro de Recuperación de Fauna Silvestre de Chinchón.', 'Descubre el trabajo de conservación de la fauna silvestre en el Centro de Recuperación de Fauna Silvestre de Chinchón, en un entorno rural cercano a la ciudad.', '2024-07-06', '10:00:00', 20),
('Safari Fotográfico en la Reserva de la Biosfera de Manzanares', 'ImagenProducto imagenProducto67', 'ImagenSecundaria animales7secundaria1', 'ImagenSecundaria animales7secundaria2', 'Manzanares el Real, Madrid', 'Madrid', 35.00, 180, 'Media', '689012345', 'Animales', 'Fotografía de naturaleza', 'Explora la riqueza natural de la Reserva de la Biosfera de Manzanares con un safari fotográfico.', 'Explora la riqueza natural de la Reserva de la Biosfera de Manzanares con un safari fotográfico que te permitirá capturar la belleza de su fauna y flora en la España vacía.', '2024-07-07', '10:00:00', 18),
('Paseo a Caballo en la Sierra de Rute', 'ImagenProducto imagenProducto68', 'ImagenSecundaria animales8secundaria1', 'ImagenSecundaria animales8secundaria2', 'Rute, Córdoba', 'Córdoba', 40.00, 180, 'Alta', '690188456', 'Animales', 'Ecoturismo', 'Disfruta de un relajante paseo a caballo por los senderos de la Sierra de Rute.', 'Disfruta de un relajante paseo a caballo por los senderos de la Sierra de Rute, explorando paisajes naturales y disfrutando de la compañía de estos majestuosos animales en un entorno rural.', '2024-07-08', '10:00:00', 12),
('Excursión para Avistar Águilas en los Picos de Europa', 'ImagenProducto imagenProducto69', 'ImagenSecundaria animales9secundaria1', 'ImagenSecundaria animales9secundaria2', 'Cabrales, Asturias', 'Asturias', 30.00, 150, 'Media', '601234567', 'Animales', 'Avistamiento de aves', 'Únete a una emocionante excursión para avistar águilas doradas en los majestuosos picos de los Picos de Europa.', 'Únete a una emocionante excursión para avistar águilas doradas en los majestuosos picos de los Picos de Europa, disfrutando de la belleza de estas aves rapaces en su hábitat natural en la España vacía.', '2024-07-09', '10:00:00', 15),
('Visita al Centro de Rescate de Animales en Llerena', 'ImagenProducto imagenProducto70', 'ImagenSecundaria animales10secundaria1', 'ImagenSecundaria animales10secundaria2', 'Llerena, Badajoz', 'Badajoz', 25.00, 120, 'Baja', '612345678', 'Animales', 'Ecoturismo', 'Descubre la labor de rescate y conservación de animales en el Centro de Rescate de Llerena.', 'Descubre la labor de rescate y conservación de animales en el Centro de Rescate de Llerena, donde podrás aprender sobre la rehabilitación de especies locales en un entorno rural próximo a la España vacía.', '2024-07-10', '10:00:00', 20);



## INSERTS DE ACTIVIDADES COSTERAS
INSERT INTO Actividades (nombre, imagen, imagen1, imagen2, localizacion, region, precio, duracion, dificultad, numTelf, tipo, categoria, descripcion, descripcionlarga, fechaInicio, hora, plazasDisponibles) 
VALUES 
('Buceo en la Reserva Marina de Cabo Palos', 'ImagenProducto imagenProducto71', 'ImagenSecundaria costeras1secundaria1', 'ImagenSecundaria costeras1secundaria2', 'Cabo Palos, Murcia', 'Murcia', 50.00, 180, 'Alta', '666456789', 'Costeras', 'Ecoturismo', 'Sumérgete en las aguas cristalinas de la Reserva Marina de Cabo Palos con una emocionante sesión de buceo.', 'Sumérgete en las aguas cristalinas de la Reserva Marina de Cabo Palos con una emocionante sesión de buceo, donde podrás descubrir un fascinante mundo submarino lleno de vida marina.', '2024-07-11', '09:00:00', 15),
('Paseo en Barco por San Vicente de la Barquera', 'ImagenProducto imagenProducto72', 'ImagenSecundaria costeras2secundaria1', 'ImagenSecundaria costeras2secundaria2', 'San Vicente de la Barquera, Cantabria', 'Cantabria', 35.00, 150, 'Media', '634567890', 'Costeras', 'Turismo cultural', 'Disfruta de un relajante paseo en barco por las hermosas aguas de San Vicente de la Barquera.', 'Disfruta de un relajante paseo en barco por las hermosas aguas de San Vicente de la Barquera, explorando la costa, descubriendo calas escondidas, cuevas marinas y espectaculares acantilados.', '2024-07-12', '10:30:00', 20),
('Surfing en la Playa de Zarautz', 'ImagenProducto imagenProducto73', 'ImagenSecundaria costeras3secundaria1', 'ImagenSecundaria costeras3secundaria2', 'Zarautz, País Vasco', 'País Vasco', 40.00, 180, 'Alta', '645699901', 'Costeras', 'Ecoturismo', 'Atrévete con las olas del Atlántico en la famosa Playa de Zarautz.', 'Atrévete con las olas del Atlántico en la famosa Playa de Zarautz, donde podrás disfrutar de emocionantes sesiones de surf y vivir la pasión por este deporte acuático.', '2024-07-13', '11:00:00', 12),
('Kayak en la Costa de Menorca', 'ImagenProducto imagenProducto74', 'ImagenSecundaria costeras4secundaria1', 'ImagenSecundaria costeras4secundaria2', 'Menorca, Islas Baleares', 'Islas Baleares', 45.00, 180, 'Alta', '656789012', 'Costeras', 'Ecoturismo', 'Navega en kayak por las aguas turquesas de la costa de Menorca.', 'Navega en kayak por las aguas turquesas de la costa de Menorca, explorando cuevas marinas, acantilados impresionantes y hermosas playas vírgenes.', '2024-07-14', '09:00:00', 18),
('Paddle Surf en la Playa de Nigrán', 'ImagenProducto imagenProducto75', 'ImagenSecundaria costeras5secundaria1', 'ImagenSecundaria costeras5secundaria2', 'Nigrán, Pontevedra', 'Pontevedra', 30.00, 120, 'Media', '667890123', 'Costeras', 'Ecoturismo', 'Disfruta de una emocionante sesión de paddle surf en la hermosa Playa de Nigrán.', 'Disfruta de una emocionante sesión de paddle surf en la hermosa Playa de Nigrán, deslizándote sobre las aguas del Atlántico y disfrutando del entorno natural de la costa gallega.', '2024-07-15', '08:30:00', 20),
('Pesca Deportiva en la Costa de Cadaqués', 'ImagenProducto imagenProducto76', 'ImagenSecundaria costeras6secundaria1', 'ImagenSecundaria costeras6secundaria2', 'Cadaqués, Girona', 'Girona', 40.00, 180, 'Alta', '678101234', 'Costeras', 'Pesca deportiva', 'Disfruta de una emocionante jornada de pesca deportiva en las aguas cristalinas de la Costa de Cadaqués.', 'Disfruta de una emocionante jornada de pesca deportiva en las aguas cristalinas de la Costa de Cadaqués, donde podrás pescar una gran variedad de especies marinas.', '2024-07-16', '07:00:00', 15),
('Avistamiento de Tortugas Marinas en Los Caños de Meca', 'ImagenProducto imagenProducto77', 'ImagenSecundaria costeras7secundaria1', 'ImagenSecundaria costeras7secundaria2', 'Los Caños de Meca, Cádiz', 'Cádiz', 35.00, 150, 'Media', '689010045', 'Costeras', 'Ecoturismo', 'Embárcate en una aventura para avistar tortugas marinas en las aguas cálidas de Los Caños de Meca.', 'Embárcate en una aventura para avistar tortugas marinas en las aguas cálidas de Los Caños de Meca, donde podrás observar estas fascinantes criaturas en su hábitat natural.', '2024-07-17', '11:00:00', 18),
('Safari Marino en Tarifa', 'ImagenProducto imagenProducto78', 'ImagenSecundaria costeras8secundaria1', 'ImagenSecundaria costeras8secundaria2', 'Tarifa, Cádiz', 'Cádiz', 40.00, 180, 'Alta', '690123400', 'Costeras', 'Avistamiento de aves', 'Únete a un safari marino en Tarifa.', 'Únete a un safari marino en Tarifa, donde podrás avistar una gran diversidad de aves marinas, delfines y ballenas en su migración anual.', '2024-07-18', '10:00:00', 12),
('Esquí Acuático en Punta Umbría', 'ImagenProducto imagenProducto79', 'ImagenSecundaria costeras9secundaria1', 'ImagenSecundaria costeras9secundaria2', 'Punta Umbría, Huelva', 'Huelva', 45.00, 180, 'Alta', '601234554', 'Costeras', 'Ecoturismo', 'Experimenta la emoción del esquí acuático en las aguas de Punta Umbría.', 'Experimenta la emoción del esquí acuático en las aguas de Punta Umbría, disfrutando del sol y las olas mientras practicas este emocionante deporte acuático.', '2024-07-19', '09:30:00', 15),
('Observación de Estrellas en Cala Sant Vicenç', 'ImagenProducto imagenProducto80', 'ImagenSecundaria costeras10secundaria1', 'ImagenSecundaria costeras10secundaria2', 'Cala Sant Vicenç, Islas Baleares', 'Islas Baleares', 25.00, 120, 'Baja', '612345789', 'Costeras', 'Observación astronómica', 'Contempla la belleza del cielo nocturno desde Cala Sant Vicenç.', 'Contempla la belleza del cielo nocturno desde Cala Sant Vicenç, en una experiencia de observación de estrellas donde podrás descubrir la magia del universo.', '2024-07-20', '20:00:00', 20);

## INSERTS DE TARJETAS BANCARIAS
INSERT INTO TarjetaBancaria (nombretitular, numerotarjeta, fechacaducidad, cvv, idusuario)
VALUES ('Juan Pérez', '1234567890123456', '2025-12-31', '123', 1);

## INSERTS DE RESERVAS
INSERT INTO Reserva (fechaEntrada, fechaSalida, numPersonas, estadoReserva, numReserva, totalPrecio, idUsuario, idAlojamiento, idActividad)
VALUES 
('2024-06-01', '2024-06-10', 2, 'Pendiente', 'ABC123', 500.00, 1, null, 1),
('2024-06-01', '2024-06-10', 2, 'Pendiente', 'ABC1523', 500.00, 1, 21, null);

SELECT * FROM Usuarios;
SELECT * FROM Alojamientos;
SELECT * FROM Actividades;
SELECT * FROM Reserva;
SELECT * FROM TarjetaBancaria;